version: '3.1'
services:
  musala:
    container_name: musala-drones-app-v1
    build:
      context: .
      dockerfile: Dockerfile


    ports:
      - 8082:8082
    expose:
      - 8082
    logging:
      driver: json-file


#docker-compose build